from __future__ import annotations

from typing import TYPE_CHECKING

import os
import logging

import Utils
from settings import get_settings
from worlds.Files import APProcedurePatch, APTokenMixin, APTokenTypes

if TYPE_CHECKING:  # imported only for type checking, avoids circular at runtime
    from . import Tomba2World

DATAHASH = "63E774AC891CA718E19A88B42C72DE06"
AUDIOHASH = "938CD585633F5C4BFF1856B807BFD8DE"
logger = logging.getLogger("Client")


# MAIN.EXE to Track 1 BIN offset mapping
#
# PS1 CDs store data in 2352-byte sectors, of which 2048 bytes are user data
# and the rest is header/EDC/ECC. When MAIN.EXE is embedded in the Track 1
# image, those extra bytes mean that a linear offset inside MAIN.EXE does not
# match the same number inside the .bin file.
#
# For Tomba 2, MAIN.EXE begins at offset 0x0000D368 in the Track 1 bin. For
# each 0x800 bytes of MAIN.EXE, the bin advances by one 0x930-byte sector,
# i.e., there is 0x130 bytes of overhead per 0x800 bytes of executable data.

MAIN_EXE_BASE = 0x0000D368  # offset of MAIN.EXE start inside Track 1 BIN
SECTOR_DATA_SIZE = 0x800    # 2048 bytes of user data per sector
SECTOR_SIZE = 0x930         # 2352 bytes per sector on disc
SECTOR_OVERHEAD = SECTOR_SIZE - SECTOR_DATA_SIZE  # 0x130 bytes overhead


def exe_to_bin_offset(exe_offset: int) -> int:
    """Convert an offset inside MAIN.EXE to a byte offset in Track 1 BIN.

    `exe_offset` is the position within MAIN.EXE (as shown by a file editor).

    Because each 0x800 bytes of executable data are stored in a 0x930-byte
    sector on disc, we add 0x130 bytes of overhead per 0x800-byte chunk.

    bin_offset = MAIN_EXE_BASE
                 + exe_offset
                 + floor(exe_offset / 0x800) * 0x130
    """

    if exe_offset < 0:
        raise ValueError("exe_offset must be non-negative")

    full_sectors = exe_offset // SECTOR_DATA_SIZE
    return MAIN_EXE_BASE + exe_offset + full_sectors * SECTOR_OVERHEAD


class Tomba2ProcedurePatch(APProcedurePatch, APTokenMixin):
    """Minimal procedure patch for Tomba 2.

    This currently only supports token-based edits (no base bsdiff yet) and is
    intended for use with a BizHawk client + Lua connector.

    - patch_file_ending: the file type generated by the Archipelago generator
      (and opened by your BizHawk client).
    - result_file_ending: the ROM / disc image extension produced by Patch.py.

    The `hash` field is left as None for now so there is no base MD5 check.
    Once you settle on an exact disc image, set this to its MD5 (or list of
    acceptable MD5s) and add a verification in get_base_iso_bytes.
    """

    game = "Tomba 2"
    hash = DATAHASH
    patch_file_ending = ".aptomba2"
    result_file_ending = ".cue"

    # For now we only rely on a token stream (token_data.bin).
    procedure = [
        ("apply_tokens", ["token_data.bin"]),
    ]

    @classmethod
    def get_source_data(cls) -> bytes:
        """Return the base PS1 disc image bytes to patch.

        This uses a very simple lookup: it first tries the given path, then the
        Archipelago user directory. You can later wire this into `settings`
        like other worlds if desired.
        """

        return get_base_iso_bytes()

    def patch(self, target: str) -> None:
        """Patch Track 1, ensure Track 2 exists, and write a .cue.

        This mirrors the SotN workflow:
        - Apply tokens to the base Track 1 BIN.
        - Rename the patched output to <name>.bin.
        - Ensure a Track 2 BIN exists by copying it from settings.
        - Emit a two-track CUE file that references both.
        """

        from settings import get_settings

        file_base = target[:-4]

        # If patched bin + cue already exist, just ensure track 2 is present.
        if os.path.exists(file_base + ".bin") and os.path.exists(file_base + ".cue"):
            audio_name = os.path.join(os.path.dirname(target),
                                      "Tomba! 2 - The Evil Swine Return (Track 2).bin")
            if not os.path.exists(audio_name):
                audio_src = get_settings().tomba2_settings.audio_file
                with open(audio_src, "rb") as src, open(audio_name, "wb") as dst:
                    dst.write(src.read())
            return

        # Let APProcedurePatch do the actual token-based patching first.
        super().patch(target)

        # Rename the patched Track 1 image to .bin.
        os.rename(target, file_base + ".bin")

        # Copy Track 2 next to the patched ROM if needed.
        audio_name = os.path.join(os.path.dirname(target),
                                  "Tomba! 2 - The Evil Swine Return (Track 2).bin")
        if not os.path.exists(audio_name):
            audio_src = get_settings().tomba2_settings.audio_file
            with open(audio_src, "rb") as src, open(audio_name, "wb") as dst:
                dst.write(src.read())

        # Build a simple two-track CUE file.
        track1_name = os.path.basename(file_base)
        cue = (
            f'FILE "{track1_name}.bin" BINARY\n'
            f'  TRACK 01 MODE2/2352\n\tINDEX 01 00:00:00\n'
            f'FILE "Tomba! 2 - The Evil Swine Return (Track 2).bin" BINARY\n'
            f'  TRACK 02 AUDIO\n\tINDEX 00 00:00:00\n\tINDEX 01 00:02:00'
        )

        with open(file_base + ".cue", "wb") as f:
            f.write(cue.encode("utf-8"))


def get_base_iso_bytes(file_name: str = "") -> bytes:
    """Load and cache the base PS1 disc image.

    For consistency with other PS1 worlds (like Symphony of the Night), this
    uses the tomba2_settings.rom_file path from Archipelago's settings. That
    should be the same file you point BizHawk at.
    """

    base_iso_bytes = getattr(get_base_iso_bytes, "base_iso_bytes", None)
    if base_iso_bytes is None:
        if not file_name:
            # Use configured ROM path if available; fall back to default name.
            try:
                file_name = get_settings().tomba2_settings.rom_file
            except Exception:
                file_name = get_base_iso_path("")
        else:
            file_name = get_base_iso_path(file_name)

        with open(file_name, "rb") as f:
            base_iso_bytes = f.read()
        setattr(get_base_iso_bytes, "base_iso_bytes", base_iso_bytes)
    return base_iso_bytes


def get_base_iso_path(file_name: str = "") -> str:
    """Resolve the path to the base PS1 disc image.

    By default this looks for a file named "Tomba! 2 - The Evil Swine Return (Track 1).bin" in
    the current working directory, then in the Archipelago user directory.

    You can change the default name or later hook this into `settings` so the
    path is configurable via host.yaml.
    """

    if not file_name:
        file_name = "Tomba! 2 - The Evil Swine Return (Track 1).bin"

    if not os.path.exists(file_name):
        # Fall back to Archipelago's per-user folder.
        file_name = Utils.user_path(file_name)

    if not os.path.exists(file_name):
        raise FileNotFoundError(
            f"Base Tomba 2 image not found: {file_name}. "
            "Place your PS1 image next to the generator or in the user "
            "directory with this exact name, or update get_base_iso_path()."
        )

    return file_name


def write_patch(world: "Tomba2World", patch: Tomba2ProcedurePatch) -> None:
    """Populate the patch with any ROM/disc changes for this slot.

    For a barebones world with only one item and no in-ROM UI changes, this
    function can be kept minimal and only emit the token stream.

    As you map out PS1 memory / file offsets, this is where you should:
    - write AP identification strings into unused ROM space so the BizHawk
        client can distinguish patched vs vanilla images;
    - write per-location item data tables the Lua script will read;
    - embed slot-specific auth data or seed IDs if desired.
    """

    # Example: write an AP marker into MAIN.EXE at a known-safe offset.
    # 0x009CE70 is the offset *inside MAIN.EXE*; exe_to_bin_offset converts
    # this into the corresponding byte offset in Track 1 BIN.
    marker_exe_offset = 0x009CE70
    marker_bin_addr = exe_to_bin_offset(marker_exe_offset)
    logger.info(
        "Tomba 2 MAIN.EXE marker mapping: exe_offset=0x%X -> bin_offset=0x%X",
        marker_exe_offset,
        marker_bin_addr,
    )
    patch.write_token(APTokenTypes.WRITE, marker_bin_addr, b"AP01TMB2")

    patch.write_token(APTokenTypes.WRITE, 0x0C1718, b"\x22\x76\xC7\x52")
    patch.write_token(APTokenTypes.WRITE, 0x0C1736, b"\x41\x95\xA7\x07\x07\x41\x7D\x3B")
    patch.write_token(APTokenTypes.WRITE, 0x0C176E, b"\xF7\x24\xAE\xBD")
    patch.write_token(APTokenTypes.WRITE, 0x0C178C, b"\xCA\x68\x6B\x8B\x2E\xAA\xE0\xA1")
    patch.write_token(APTokenTypes.WRITE, 0x0C17C4, b"\xED\x02\x11\x2D")
    patch.write_token(APTokenTypes.WRITE, 0x0C17CE, b"\x2C\x3C\x78\x6A\xD3\xA2\x58\x93\xF2\x41\x25\x2C\x38\x0F\x3F\xA1\x12\xE6\x17\xD8\xF2")
    patch.write_token(APTokenTypes.WRITE, 0x0C1802, b"\xE8\x1E\x22\x38\x7A\xA2\x73\xB4\xAA\x0E\x52\x52\xF2\x1B\x07")
    patch.write_token(APTokenTypes.WRITE, 0x0C1811, b"\x1A\x52\xB0\x39\x43")

    # Serialize the token list into the container.
    patch.write_file("token_data.bin", patch.get_token_binary())
